### ISSUE TITLE
Panic on executing a 32-bit static linux binary

### ISSUE THREAD

**Issue by petevine** [lunixbochs/usercorn#101]
Trying to run `./usercorn ~/go/bin/oh` on 32-bit linux ends in:

````

panic: Kernel not found for syscall 'modify_ldt'

goroutine 17 [running, locked to thread]:
github.com/lunixbochs/usercorn/go.(*Usercorn).Syscall(0x1851e100, 0x7b, 0x825f3c0, 0xa, 0x18511ae0, 0x18511ae0, 0x0, 0x0, 0x0)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/usercorn.go:586 +0x5e6
github.com/lunixbochs/usercorn/go/arch/x86.LinuxSyscall(0xb27eaa78, 0x1851e100)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/arch/x86/linux.go:22 +0xdd
github.com/lunixbochs/usercorn/go/arch/x86.LinuxInterrupt(0xb27eaa78, 0x1851e100, 0x80)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/arch/x86/linux.go:28 +0x35
github.com/lunixbochs/usercorn/go.(*Usercorn).addHooks.func5(0xb27eaa00, 0x185a2880, 0x80)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/usercorn.go:465 +0x53
github.com/unicorn-engine/unicorn/bindings/go/unicorn.hookInterrupt(0xb30261f0, 0x80, 0x185a3250)
        /home/petevine/go1.5/src/github.com/unicorn-engine/unicorn/bindings/go/unicorn/hook.go:42 +0x41

goroutine 1 [syscall, locked to thread]:
github.com/unicorn-engine/unicorn/bindings/go/unicorn._Cfunc_uc_emu_start(0xb30261f0, 0x8096490, 0x0, 0xffffffff, 0xffffffff, 0x0, 0x0, 0x0, 0x0)
        github.com/unicorn-engine/unicorn/bindings/go/unicorn/_obj/_cgo_gotypes.go:123 +0x37
github.com/unicorn-engine/unicorn/bindings/go/unicorn.(*uc).StartWithOptions(0x185a2880, 0x8096490, 0x0, 0xffffffff, 0xffffffff, 0x1854fd28, 0x0, 0x0)
        /home/petevine/go1.5/src/github.com/unicorn-engine/unicorn/bindings/go/unicorn/unicorn.go:80 +0x6c
github.com/unicorn-engine/unicorn/bindings/go/unicorn.(*uc).Start(0x185a2880, 0x8096490, 0x0, 0xffffffff, 0xffffffff, 0x0, 0x0)
        /home/petevine/go1.5/src/github.com/unicorn-engine/unicorn/bindings/go/unicorn/unicorn.go:85 +0x72
github.com/lunixbochs/usercorn/go.(*Usercorn).Run(0x1851e100, 0x1850a188, 0x1, 0x1, 0x1850c380, 0x36, 0x36, 0x0, 0x0)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/usercorn.go:168 +0xdbb
main.main()
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/usercorn/cli.go:82 +0x89f

goroutine 18 [syscall, locked to thread]:
runtime.goexit()
        /home/petevine/go/src/runtime/asm_386.s:1662 +0x1
````

**Comment by lunixbochs** [comment]
Just a missing syscall. Need to "subclass" the Linux kernel in arch/x86 just like it is in x86_64, and add a function ModifyLdt like this http://linux.die.net/man/2/modify_ldt

I'm assuming this is followed by a syscall to set FS or GS? Can you strace the process running normally and post that?

**Comment by petevine** [comment]
Here you are:
[oh_trace.txt](https://github.com/lunixbochs/usercorn/files/41300/oh_trace.txt)

**Comment by lunixbochs** [comment]
fwiw there's no threading yet, which is tracked in some upstream Unicorn issue

**Comment by petevine** [comment]
What's the most complex kind of binary usercorn can handle at the moment?

**Comment by lunixbochs** [comment]
Many features from busybox x86_64 work.

**Comment by petevine** [comment]
The 64-bit busybox binary prints the help screen without a problem indeed, but for example:

`busybox-x86_64 ls -l` => `panic: Kernel not found for syscall getdents64`
`busybox-x86_64 whoami` => `panic: Kernel not found for syscall geteuid`
`busybox-x86_64 df`  => `panic: Kernel not found for syscall statfs`

and so on probably.

The 32-bit busybox on the other hand just goes:

`panic: Kernel not found for syscall 'set_thread_area'`

**Comment by lunixbochs** [comment]
Yes, I've tried most of them already. I'm currently prioritizing fixing dynamic linker support over adding syscalls, though adding a syscall can be pretty easy if you want to try it.

**Comment by petevine** [comment]
Could you add one so I can analyse the commit and see if it's easy enough :)

**Comment by lunixbochs** [comment]
Here are some examples:

Simple:

 - dup https://github.com/lunixbochs/usercorn/commit/0e03b06e78b2c979827b962235958a8395416b1b
 - chroot https://github.com/lunixbochs/usercorn/commit/5764eda47221324699f79ed803544c63c2e2c2cb
 - link https://github.com/lunixbochs/usercorn/commit/ba7d5c14e463cf7dc37cf252b939c5cc90ab1333

The harder ones I've been working on are socket and file related, like select and getdents64

 - getdents https://github.com/lunixbochs/usercorn/blob/master/go/kernel/linux/io.go#L15

An easy one to add for practice would be Geteuid() in go/kernel/posix/user.go.

**Comment by petevine** [comment]
Thanks a lot, I'll see what I can do.

**Comment by lunixbochs** [comment]
Reference for `modify_ldt`:

https://github.com/lunixbochs/qemu/blob/master/linux-user/syscall.c#L4228
https://github.com/lunixbochs/qemu/blob/master/linux-user/syscall.c#L4116
https://github.com/lunixbochs/qemu/blob/master/linux-user/syscall.c#L4228

**Comment by lunixbochs** [comment]
getdents64 implemented :)

**Comment by petevine** [comment]
Indeed, ls still saying `no` though :)
````
./usercorn ~/Downloads/busybox-x86_64 ls -l go/usercorn
total 0
````

**Comment by lunixbochs** [comment]
I get an error with ls -l on go/usercorn but not on other directories. Probably an issue with folders containing almost no files.

**Comment by petevine** [comment]
I can see `ls -l` from busybox-x86_64  can already print everything very nicely, except for the first line which always shows: `total 0`

The story with busybox-armv5 is a little different:
`?rwxr-x--t    0 4096     4096     6263160923420188828 Jan  1  1970 .`
invalid fetch: @0x400001d0, 0x1 = 0x0

This looks familiar except it used to happen at the end, after successful execution:
https://github.com/lunixbochs/usercorn/issues/148

**Comment by lunixbochs** [comment]
getdents likely needs to be adapted to support the arm struct packing format

**Comment by lunixbochs** [comment]
the arm crash at end was fixed by e4d77cd

**Comment by petevine** [comment]
Nope, I've not managed to discover anything new.
