### ISSUE TITLE
Command fails silently

### ISSUE THREAD

**Issue by petevine** [lunixbochs/usercorn#109]
For example:

`./usercorn ~/Downloads/busybox-x86_64 pidof foo-app`

prints nothing as if it `returned 0` but there was a running foo-app so it should have been:

````
qemu-x86_64 Downloads/busybox-x86_64 pidof foo-app
27542
````

Only in the trace do we find it actually failed:
````
s panic: reflect: call of reflect.Value.Interface on zero Value

goroutine 17 [running, locked to thread]:
reflect.valueInterface(0x0, 0x0, 0x0, 0xb06e2501, 0x0, 0x0)
        /home/petevine/go/src/reflect/value.go:906 +0x6a
reflect.Value.Interface(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/petevine/go/src/reflect/value.go:901 +0x42
github.com/lunixbochs/usercorn/go/kernel/common.Syscall.traceArg(0x185bc9c0, 0xa, 0x824e8a0, 0x1850f4a0, 0x16, 0x8263de0, 0x9, 0x0, 0x0, 0xb06e2068, ...)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/kernel/common/trace.go:32 +0x7e7
github.com/lunixbochs/usercorn/go/kernel/common.Syscall.traceArgs(0x185bc9c0, 0xa, 0x824e8a0, 0x1850f4a0, 0x16, 0x8263de0, 0x9, 0x0, 0x0, 0xb06e2068, ...)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/kernel/common/trace.go:42 +0x161
github.com/lunixbochs/usercorn/go/kernel/common.Syscall.Trace(0x185bc9c0, 0xa, 0x824e8a0, 0x1850f4a0, 0x16, 0x8263de0, 0x9, 0x0, 0x0, 0xb06e2068, ...)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/kernel/common/trace.go:48 +0x55
github.com/lunixbochs/usercorn/go.(*Usercorn).Syscall(0x185be000, 0x9e, 0x8267000, 0xa, 0x1884fd80, 0x1884fd80, 0x0, 0x0, 0x0)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/usercorn.go:625 +0x3d9
github.com/lunixbochs/usercorn/go/arch/x86_64.LinuxSyscall(0xb06e25a0, 0x185be000)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/arch/x86_64/linux.go:61 +0xdd
github.com/lunixbochs/usercorn/go/arch/x86_64.AbiInit.func1(0xb06e2528, 0x185bc920)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/arch/x86_64/abi.go:13 +0x35
github.com/unicorn-engine/unicorn/bindings/go/unicorn.hookX86Syscall(0xb0f1e158, 0x186e2c70)
        /home/petevine/go1.5/src/github.com/unicorn-engine/unicorn/bindings/go/unicorn/hook.go:60 +0x39

goroutine 1 [syscall, locked to thread]:
github.com/unicorn-engine/unicorn/bindings/go/unicorn._Cfunc_uc_emu_start(0xb0f1e158, 0x400194, 0x0, 0xffffffff, 0xffffffff, 0x0, 0x0, 0x0, 0x0)
        github.com/unicorn-engine/unicorn/bindings/go/unicorn/_obj/_cgo_gotypes.go:123 +0x37
github.com/unicorn-engine/unicorn/bindings/go/unicorn.(*uc).StartWithOptions(0x185bc920, 0x400194, 0x0, 0xffffffff, 0xffffffff, 0x1854fbd8, 0x0, 0x0)
        /home/petevine/go1.5/src/github.com/unicorn-engine/unicorn/bindings/go/unicorn/unicorn.go:81 +0x6c
github.com/unicorn-engine/unicorn/bindings/go/unicorn.(*uc).Start(0x185bc920, 0x400194, 0x0, 0xffffffff, 0xffffffff, 0x0, 0x0)
        /home/petevine/go1.5/src/github.com/unicorn-engine/unicorn/bindings/go/unicorn/unicorn.go:86 +0x72
github.com/lunixbochs/usercorn/go.(*Usercorn).Run(0x185be000, 0x1850a1c0, 0x3, 0x4, 0x185ba000, 0x36, 0x40, 0x0, 0x0)
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/usercorn.go:181 +0xdbe
main.main()
        /home/petevine/go/src/github.com/lunixbochs/usercorn/go/usercorn/cli.go:124 +0xe3e

goroutine 18 [syscall, locked to thread]:
runtime.goexit()
        /home/petevine/go/src/runtime/asm_386.s:1662 +0x1
````

**Comment by lunixbochs** [comment]
no, that error is -strace failing to decode parameters for a syscall

**Comment by petevine** [comment]
OK, I get it - it could print something like `unsupported syscall <unknown>`?

**Comment by lunixbochs** [comment]
No, the problem you encountered was a bug in usercorn that should be fixed in latest master. It wasn't a missing syscall, it was an error during syscall argument decode in the trace.

**Comment by petevine** [comment]
Next time I'm on x86 I'll check it out; I'm pretty sure however I'd already had the latest unstable.

**Comment by petevine** [comment]
Yes, you were right but it must have been about upstream as I'd already been up to date.

**Comment by petevine** [comment]
Another command that fails silently: `lsof`

Once you implement `/proc` support this issue will disappear but until then why not print the strace instead?

Here's a question for ya! :)

**Comment by lunixbochs** [comment]
if you want to print the strace, you can run with `-strace`

**Comment by petevine** [comment]
That's how I confirmed I was up-to-date. Never mind, it's just a missing feature and not some random error.

**Comment by lunixbochs** [comment]
I'm not sure what you're asking for here.

**Comment by petevine** [comment]
Now that's much better! :)

```bash
$ ./usercorn ~/Downloads/busybox-x86_64 pidof foo
pidof: can't open '/proc': Invalid argument
````

**Comment by petevine** [comment]
I thought you changed something but it turns out it's still quiet on x86 host. Any idea where the difference is coming from?
