### ISSUE TITLE
invalid fetch on arm busybox exit

### ISSUE THREAD

**Issue by lunixbochs** [lunixbochs/usercorn#148]
https://github.com/lunixbochs/usercorn/issues/52#issuecomment-172736414

**Comment by petevine** [comment]
I missed the second part of that comment (email); where am I supposed to put the breakpoint in?

**Comment by petevine** [comment]
I missed the second part of that comment (email); where am I supposed to put the breakpoint in?

**Comment by lunixbochs** [comment]
At the failing address `0x400001d0`, in theory. See if it executes at all on hardware.

Can also do a `catch syscall exit` and get a backtrace.

Third debugging option is to break on main, then do `finish` and single-step out of the program, then compare that execution path against Usercorn

**Comment by petevine** [comment]
Before I start, I think there's a problem with debug output in usercorn on my system. I'll open a separate issue and delete this comment in a moment.

**Comment by petevine** [comment]
Ok, re number 1:
```shell
(gdb) b *0x400001d0
Breakpoint 1 at 0x400001d0
(gdb) run whoami
Starting program: /home/odroid/usercorn-kit/busybox-armv5l whoami
Error in re-setting breakpoint 1: Warning:
Cannot insert breakpoint 1.
Cannot access memory at address 0x400001d0
````

Re number 2:
```shell
(gdb) catch syscall exit
Catchpoint 1 (syscall 'exit' [1])
(gdb) catch syscall exit_group
Catchpoint 2 (syscall 'exit_group' [248])
(gdb) run whoami
Starting program: /home/odroid/usercorn-kit/busybox-armv5l whoami
odroid

Catchpoint 2 (call to syscall exit_group), 0x000cae6c in ?? ()
(gdb) bt
#0  0x000cae6c in ?? ()
#1  0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) c
Continuing.
[Inferior 1 (process 11655) exited normally]
````

**Comment by petevine** [comment]
Re 3: The binary doesn't have any debugging symbols (checked with `nm`) so after locating the entry point:

```shell
(gdb) b *0x81d0
Breakpoint 1 at 0x81d0
(gdb) run whoami
Starting program: /home/odroid/usercorn-kit/busybox-armv5l whoami

Breakpoint 1, 0x000081d0 in ?? ()
(gdb) x/64i $pc
=> 0x81d0:      mov     r11, #0
   0x81d4:      mov     lr, #0
   0x81d8:      pop     {r1}            ; (ldr r1, [sp], #4)
   0x81dc:      mov     r2, sp
   0x81e0:      push    {r2}            ; (str r2, [sp, #-4]!)
   0x81e4:      push    {r0}            ; (str r0, [sp, #-4]!)
   0x81e8:      ldr     r12, [pc, #16]  ; 0x8200
   0x81ec:      push    {r12}           ; (str r12, [sp, #-4]!)
   0x81f0:      ldr     r0, [pc, #12]   ; 0x8204
   0x81f4:      ldr     r3, [pc, #12]   ; 0x8208
   0x81f8:      b       0xe78c0
   0x81fc:      bl      0xe2e24
   0x8200:      strdeq  lr, [lr], -r12
   0x8204:      andeq   r8, r0, r8, ror r9
   0x8208:      ldrdeq  r8, [r0], -r4
   0x820c:      push    {lr}            ; (str lr, [sp, #-4]!)
   0x8210:      sub     sp, sp, #4
   0x8214:      b       0x8230
   0x8218:      ldrb    r2, [r1, #-1]
   0x821c:      sub     r3, r2, #9
   0x8220:      cmp     r2, #32
   0x8224:      cmpne   r3, #4
   0x8228:      mov     r1, r12
   0x822c:      bhi     0x823c
   0x8230:      cmp     r1, r0
   0x8234:      sub     r12, r1, #1
   0x8238:      bhi     0x8218
   0x823c:      mov     r3, #0
   0x8240:      strb    r3, [r12, #1]
   0x8244:      bl      0x9288
   0x8248:      add     sp, sp, #4
   0x824c:      pop     {lr}            ; (ldr lr, [sp], #4)
   0x8250:      bx      lr
   0x8254:      ldr     r3, [pc, #44]   ; 0x8288
   0x8258:      push    {lr}            ; (str lr, [sp, #-4]!)
   0x825c:      add     r3, r3, r1, lsl #1
   0x8260:      ldrh    r1, [r3, #-2]
   0x8264:      ldr     r3, [pc, #32]   ; 0x828c
   0x8268:      lsl     r1, r1, #20
   0x826c:      lsr     r1, r1, #20
   0x8270:      sub     sp, sp, #4
   0x8274:      add     r1, r1, r3
   0x8278:      bl      0xdb690
   0x827c:      add     sp, sp, #4
   0x8280:      pop     {lr}            ; (ldr lr, [sp], #4)
   0x8284:      bx      lr
   0x8288:      ldrdeq  pc, [lr], -r4
   0x828c:      andeq   lr, lr, r11, lsr #29
   0x8290:      push    {r4, lr}
   0x8294:      mov     r4, r0
   0x8298:      bl      0xce940
   0x829c:      ldr     r3, [pc, #16]   ; 0x82b4
   0x82a0:      str     r0, [r3]
   0x82a4:      ldr     r3, [pc, #12]   ; 0x82b8
   0x82a8:      str     r4, [r3]
   0x82ac:      pop     {r4, lr}
   0x82b0:      bx      lr
   0x82b4:      andseq  pc, r2, r4, lsl r3      ; <UNPREDICTABLE>
   0x82b8:      andseq  lr, r2, r12, lsl #6
   0x82bc:      push    {lr}            ; (str lr, [sp, #-4]!)
   0x82c0:      mov     r1, #1
   0x82c4:      ldr     r12, [pc, #32]  ; 0x82ec
   0x82c8:      sub     sp, sp, #12
   0x82cc:      mov     r2, #356        ; 0x164
````

**Comment by lunixbochs** [comment]
panic on exit has been fixed
