### ISSUE TITLE
aarch64 binaries

### ISSUE THREAD

**Issue by petevine** [lunixbochs/usercorn#172]
So I found this aarch64 busybox binary that's identified as:

`busybox_static: ELF 64-bit LSB  shared object, ARM aarch64, version 1 (SYSV), dynamically linked (uses shared libs), stripped`

Usercorn says:

`panic: Unsupported machine: EM_ALPHA_STD+142`

Is it an android binary or sth? Should aarch64 linux binaries work?

**Comment by lunixbochs** [comment]
I haven't tested aarch64 anything yet. Don't even know the syscall ABI offhand. We do have an arm64 arch backend that has no OS support yet, and it looks like the ELF loader doesn't know about AARCH64 either.

**Comment by petevine** [comment]
Right, I'm aware there's just unicorn support for aarch64 at the moment, but was wondering if the transition to aarch64 would reuse much of the x86_64 Linux stuff, similar to x86 -> ARM previously.

**Comment by lunixbochs** [comment]
1972574e6877f3bc8b3dad747fcbc472dc48693a

**Comment by lunixbochs** [comment]
Okay I wired the kernel and the android static binaries aren't *static* at all. They rely on the android arm64 linker `/system/bin/linker64`. I added a `-nointerp` flag and that didn't help.

**Comment by petevine** [comment]
I'll have to find a Linux aarch64 busybox binary then.

**Comment by petevine** [comment]
I think usercorn is trying to run it through the x86_64 backed:

```shell
$ gdb --args ./usercorn busybox-armv8

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xa9788460 (LWP 23629)]
0x00000000 in ?? ()
(gdb) bt
#0  0x00000000 in ?? ()
#1  0xaca2ed3e in cpu_tb_exec_x86_64 (cpu=<error reading variable: Cannot access memory at address 0x4>, 
    tb_ptr=<error reading variable: Cannot access memory at address 0x0>)
    at /unicorn/qemu/cpu-exec.c:295
````

**Comment by petevine** [comment]
Sorry, I clicked the wrong link, one notch above arm64, but discovered a bug I believe!
I'll move this stuff to the relevant issue and then post the correct data here.

**Comment by petevine** [comment]
```shell
$ ./usercorn busybox-armv8 
panic: unhandled ARM interrupt: 2

goroutine 17 [running, locked to thread]:
github.com/lunixbochs/usercorn/go/arch/arm64.LinuxInterrupt(0xaaa936e8, 0x10661960, 0x2)
        /home/odroid/go/src/github.com/lunixbochs/usercorn/go/arch/arm64/linux.go:40 +0x104
github.com/lunixbochs/usercorn/go.(*Usercorn).addHooks.func5(0xaaa93628, 0x106efbf0, 0x2)
        /home/odroid/go/src/github.com/lunixbochs/usercorn/go/usercorn.go:528 +0x84
github.com/unicorn-engine/unicorn/bindings/go/unicorn.hookInterrupt(0x4971f0, 0x2, 0x10890ea0)
        /home/odroid/go/src/github.com/unicorn-engine/unicorn/bindings/go/unicorn/hook.go:45 +0x80

goroutine 1 [syscall, locked to thread]:
github.com/unicorn-engine/unicorn/bindings/go/unicorn._Cfunc_uc_emu_start(0x4971f0, 0x40f920, 0x0, 0xffffffff, 0xffffffff, 0x0, 0x0, 0x0, 0x0)
        ??:0 +0x34
github.com/unicorn-engine/unicorn/bindings/go/unicorn.(*uc).StartWithOptions(0x106efbf0, 0x40f920, 0x0, 0xffffffff, 0xffffffff, 0x1064b9ac, 0x0, 0x0)
        /home/odroid/go/src/github.com/unicorn-engine/unicorn/bindings/go/unicorn/unicorn.go:91 +0x70
github.com/unicorn-engine/unicorn/bindings/go/unicorn.(*uc).Start(0x106efbf0, 0x40f920, 0x0, 0xffffffff, 0xffffffff, 0x0, 0x0)
````

**Comment by lunixbochs** [comment]
syscall is at least invoked in unstable now

**Comment by petevine** [comment]
Yup, funny armv5-7 never needed that syscall. (`sched_get_priority_min`)

**Comment by lunixbochs** [comment]
The syscall seems bogus. My guess is the number table is wrong.

**Comment by petevine** [comment]
Ok, I've got an arm64 unistd32.h here, straight from `4.4.6` source - how do I regenerate the table?

**Comment by lunixbochs** [comment]
I need unistd64 with all the NR_sys_write defines, just pastebin it and I'll include in ghostrace

**Comment by petevine** [comment]
Have a look [here](https://packages.debian.org/search?suite=jessie&arch=arm64&mode=filename&searchon=contents&keywords=unistd) - they don't seem to follow that naming convention.

**Comment by lunixbochs** [comment]
asm/unistd.h should be right then

**Comment by petevine** [comment]
http://pastebin.com/nGYH487Y

**Comment by petevine** [comment]
Wasn't the file a little short for the purpose?

**Comment by petevine** [comment]
I've converted my Cortex-A53 Android TV to Linux (remember that cool deal?) - what's the state of usercorn on aarch64?

**Comment by lunixbochs** [comment]
Emulating aarch64 bins, or running on an aarch64 host? I don't have any good hosts to test on, and I don't remember how well guest bins run. It's likely missing the kernel bridge.

**Comment by petevine** [comment]
This issue was about bins, so let's just settle down for host :) No problems there?

**Comment by lunixbochs** [comment]
Oh yeah, still need to figure out the syscall number mapping.

**Comment by petevine** [comment]
The new platform can run 32-bit ARM binaries natively so it seems the latter can be achieved by simply running a current `ARMv7` build.

**Comment by petevine** [comment]
Yeah, that works out of the box.

**Comment by MagaTailor** [comment]
Which parts of the usercorn framework are still missing for native `aarch64` support to materialise?

**Comment by kkszysiu** [comment]
Hey guys,

I'm also interested in aarch64 support.

**Comment by lunixbochs** [comment]
Is the primary interest for Linux or Android?

**Comment by kkszysiu** [comment]
@lunixbochs in my case it's Linux :)

**Comment by kkszysiu** [comment]
@lunixbochs do you have the code of examples from ./bins/ directory? I can compile it on Aarch64 and make a PR for easier debugging.

**Comment by lunixbochs** [comment]
That's from my lib43 project which doesn't have aarch64 support yet (though it would be easy to add).

For basic debugging Busybox is a good start.

**Comment by kkszysiu** [comment]
So far I've only compiled simple C hello world:

```c
#include <stdio.h>

int main(int argc, char *argv[])
{
  printf("Hello AArch64!\n");
  return 0;
}
```

```
file ./bins/x86_64.linux.elf
./bins/x86_64.linux.elf: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=fcc18bd0b6522f57e9f523c82a1cd19addba3722, not stripped
```

And this is what usercorn is returning while executing that file:
```
./usercorn ./bins/arm64.linux.elf

+++ caught panic +++
Kernel not found for syscall 'sched_get_priority_min'


[memory map]
[registers]
[callstack]
  0x0
%!(EXTRA string=0x0)panic: Kernel not found for syscall 'sched_get_priority_min' [recovered]
	panic: Kernel not found for syscall 'sched_get_priority_min'

goroutine 1 [running]:
github.com/lunixbochs/usercorn/go.(*Usercorn).Run.func1(0xc420142200)
	/Users/kkszysiu/Projects/Stuff/usercorn/.gopath/src/github.com/lunixbochs/usercorn/go/usercorn.go:399 +0x4f2
panic(0x43efe80, 0xc4201e2ea0)
	/Users/kkszysiu/Projects/Stuff/usercorn/deps/go-x86_64-Darwin/src/runtime/panic.go:491 +0x283
github.com/lunixbochs/usercorn/go.(*Usercorn).Syscall(0xc420142200, 0xa0, 0x4464998, 0x16, 0xc420144570, 0xc420144570, 0x12, 0x0)
	/Users/kkszysiu/Projects/Stuff/usercorn/.gopath/src/github.com/lunixbochs/usercorn/go/usercorn.go:800 +0x7d3
github.com/lunixbochs/usercorn/go/arch/arm64.LinuxSyscall(0x46ce160, 0xc420142200, 0xa0)
	/Users/kkszysiu/Projects/Stuff/usercorn/.gopath/src/github.com/lunixbochs/usercorn/go/arch/arm64/linux.go:38 +0xd8
github.com/lunixbochs/usercorn/go/arch/arm64.LinuxInterrupt(0x46ce160, 0xc420142200, 0xc400000002)
	/Users/kkszysiu/Projects/Stuff/usercorn/.gopath/src/github.com/lunixbochs/usercorn/go/arch/arm64/linux.go:45 +0x65
github.com/lunixbochs/usercorn/go.(*Usercorn).addHooks.func2(0x46c9620, 0xc420048b50, 0x2)
	/Users/kkszysiu/Projects/Stuff/usercorn/.gopath/src/github.com/lunixbochs/usercorn/go/usercorn.go:597 +0x49
github.com/lunixbochs/usercorn/go/cpu/unicorn.(*UnicornCpu).HookAdd.func3(0x46ca340, 0xc42000cda0, 0xc400000002)
	/Users/kkszysiu/Projects/Stuff/usercorn/.gopath/src/github.com/lunixbochs/usercorn/go/cpu/unicorn/unicorn.go:53 +0x45
github.com/unicorn-engine/unicorn/bindings/go/unicorn.hookInterrupt(0x7000000, 0x2, 0x1)
	/Users/kkszysiu/Projects/Go/src/github.com/unicorn-engine/unicorn/bindings/go/unicorn/hook.go:80 +0x71
github.com/unicorn-engine/unicorn/bindings/go/unicorn._cgoexpwrap_5df61e954c57_hookInterrupt(0x7000000, 0x10e00000002, 0x1)
	github.com/unicorn-engine/unicorn/bindings/go/unicorn/_obj/_cgo_gotypes.go:637 +0x3d
github.com/unicorn-engine/unicorn/bindings/go/unicorn._Cfunc_uc_emu_start(0x7000000, 0x400958, 0xffffffffffffffff, 0x0, 0x0, 0xc400000000)
	github.com/unicorn-engine/unicorn/bindings/go/unicorn/_obj/_cgo_gotypes.go:236 +0x50
github.com/unicorn-engine/unicorn/bindings/go/unicorn.(*uc).StartWithOptions.func1(0x7000000, 0x400958, 0xffffffffffffffff, 0x0, 0x0, 0x1)
	/Users/kkszysiu/Projects/Go/src/github.com/unicorn-engine/unicorn/bindings/go/unicorn/unicorn.go:110 +0x8c
github.com/unicorn-engine/unicorn/bindings/go/unicorn.(*uc).StartWithOptions(0xc42000cda0, 0x400958, 0xffffffffffffffff, 0xc4200d3950, 0xc42001bbb0, 0xc42001bbb8)
	/Users/kkszysiu/Projects/Go/src/github.com/unicorn-engine/unicorn/bindings/go/unicorn/unicorn.go:110 +0x5c
github.com/unicorn-engine/unicorn/bindings/go/unicorn.(*uc).Start(0xc42000cda0, 0x400958, 0xffffffffffffffff, 0xc4200d39d0, 0x43482ab)
	/Users/kkszysiu/Projects/Go/src/github.com/unicorn-engine/unicorn/bindings/go/unicorn/unicorn.go:115 +0x5b
github.com/lunixbochs/usercorn/go/cpu/unicorn.(*UnicornCpu).Start(0xc420048b50, 0x400958, 0xffffffffffffffff, 0x0, 0x400958)
	<autogenerated>:1 +0x53
github.com/lunixbochs/usercorn/go.(*Usercorn).Start(0xc420142200, 0x400958, 0xffffffffffffffff, 0x0, 0x0)
	/Users/kkszysiu/Projects/Stuff/usercorn/.gopath/src/github.com/lunixbochs/usercorn/go/usercorn.go:511 +0x54
github.com/lunixbochs/usercorn/go.(*Usercorn).Run(0xc420142200, 0x0, 0x0)
	/Users/kkszysiu/Projects/Stuff/usercorn/.gopath/src/github.com/lunixbochs/usercorn/go/usercorn.go:455 +0x316
github.com/lunixbochs/usercorn/go/cmd.(*UsercornCmd).Run(0xc42008a2d0, 0xc42000c060, 0x2, 0x2, 0xc420010580, 0x2c, 0x2c, 0x0)
	/Users/kkszysiu/Projects/Stuff/usercorn/.gopath/src/github.com/lunixbochs/usercorn/go/cmd/cmd.go:426 +0x1dab
main.main()
	/Users/kkszysiu/Projects/Stuff/usercorn/go/cmd/usercorn/main.go:10 +0x83
```

**Comment by lunixbochs** [comment]
I think the arm64 linux syscall number tables need to be tracked down

**Comment by lunixbochs** [comment]
arm64 busybox is working in latest unstable (make sure to run `make get` to update ghostrace and get the syscall tables)

**Comment by MagaTailor** [comment]
I've built usercorn on ARMv7 and it doesn't work for me. Are there any special requirements re: unicorn revision or is it just a 32-bit issue?

`$ ./usercorn busybox-armv8` 
```go
+++ caught panic +++
unhandled ARM interrupt: 1


[memory map]
[registers]
[callstack]
  0x0
panic: unhandled ARM interrupt: 1 [recovered]
        panic: unhandled ARM interrupt: 1

goroutine 1 [running]:
github.com/lunixbochs/usercorn/go.(*Usercorn).Run.func1(0x109b8640)
        ../github.com/lunixbochs/usercorn/go/usercorn.go:399 +0xc4
panic(0x366980, 0x10bba560)
        ../go1.8/src/runtime/panic.go:489 +0x288
github.com/lunixbochs/usercorn/go/arch/arm64.LinuxInterrupt(0x5c1b20, 0x109b8640, 0x1)
        ../github.com/lunixbochs/usercorn/go/arch/arm64/linux.go:48 +0xec
github.com/lunixbochs/usercorn/go.(*Usercorn).addHooks.func2(0x5bf0b8, 0x109706a0, 0x1)
        ../github.com/lunixbochs/usercorn/go/usercorn.go:597 +0x3c
github.com/lunixbochs/usercorn/go/cpu/unicorn.(*UnicornCpu).HookAdd.func3(0x5bf8f0, 0x109f0e80, 0x1)
        ../github.com/lunixbochs/usercorn/go/cpu/unicorn/unicorn.go:53 +0x38
github.com/unicorn-engine/unicorn/bindings/go/unicorn.hookInterrupt(0x5ed780, 0x1, 0x1)
        ../github.com/unicorn-engine/unicorn/bindings/go/unicorn/hook.go:80 +0x5c
github.com/unicorn-engine/unicorn/bindings/go/unicorn._cgoexpwrap_5df61e954c57_hookInterrupt(0x5ed780, 0x1, 0x1)
        github.com/unicorn-engine/unicorn/bindings/go/unicorn/_obj/_cgo_gotypes.go:636 +0x2c
github.com/unicorn-engine/unicorn/bindings/go/unicorn._Cfunc_uc_emu_start(0x5ed780, 0x40f920, 0x0, 0xffffffff, 0xffffffff, 0x0, 0x0, 0x0, 0x0)
        github.com/unicorn-engine/unicorn/bindings/go/unicorn/_obj/_cgo_gotypes.go:235 +0x38
github.com/unicorn-engine/unicorn/bindings/go/unicorn.(*uc).StartWithOptions.func1(0x5ed780, 0x40f920, 0x0, 0xffffffff, 0xffffffff, 0x0, 0x0, 0x0, 0x134d8c)
        ../github.com/unicorn-engine/unicorn/bindings/go/unicorn/unicorn.go:110 +0x7c
github.com/unicorn-engine/unicorn/bindings/go/unicorn.(*uc).StartWithOptions(0x109f0e80, 0x40f920, 0x0, 0xffffffff, 0xffffffff, 0x1094bca0, 0x5ed780, 0x104)
        ../github.com/unicorn-engine/unicorn/bindings/go/unicorn/unicorn.go:110 +0x5c
github.com/unicorn-engine/unicorn/bindings/go/unicorn.(*uc).Start(0x109f0e80, 0x40f920, 0x0, 0xffffffff, 0xffffffff, 0x0, 0x2ff718)
        ../github.com/unicorn-engine/unicorn/bindings/go/unicorn/unicorn.go:115 +0x60
github.com/lunixbochs/usercorn/go/cpu/unicorn.(*UnicornCpu).Start(0x109706a0, 0x40f920, 0x0, 0xffffffff, 0xffffffff, 0x40f920, 0x0)
        <autogenerated>:18 +0x6c
github.com/lunixbochs/usercorn/go.(*Usercorn).Start(0x109b8640, 0x40f920, 0x0, 0xffffffff, 0xffffffff, 0x0, 0x4c)
        ../github.com/lunixbochs/usercorn/go/usercorn.go:511 +0x54
github.com/lunixbochs/usercorn/go.(*Usercorn).Run(0x109b8640, 0x0, 0x0)
        ../github.com/lunixbochs/usercorn/go/usercorn.go:455 +0x278
github.com/lunixbochs/usercorn/go/cmd.(*UsercornCmd).Run(0x1096e9f0, 0x10982040, 0x2, 0x2, 0x1095ec80, 0x4c, 0x4c, 0x0)
        ../github.com/lunixbochs/usercorn/go/cmd/cmd.go:426 +0x1824
main.main()
        ../usercorn-unstable/go/cmd/usercorn/main.go:10 +0x68
```

**Comment by lunixbochs** [comment]
are you on the latest unstable branch? any output with the -trace flag?

**Comment by MagaTailor** [comment]
Yes, latest unstable, see the attached trace log.
[armv8-log.txt](https://github.com/lunixbochs/usercorn/files/1543450/armv8-log.txt)

**Comment by lunixbochs** [comment]
That looks like a NEON exception. I probably need to initialize the FPU

**Comment by lunixbochs** [comment]
Can you provide a link to your test binary?

**Comment by MagaTailor** [comment]
Here you are:
[busybox.zip](https://github.com/lunixbochs/usercorn/files/1543625/busybox.zip)
