### ISSUE TITLE
Python: x86_64 darwin fails on exit

### ISSUE THREAD

**Issue by lunixbochs** [lunixbochs/usercorn#22]
hello with printf: world
  args (11):
    01 @0x1000001 = "bins/x86_64.darwin.macho"
  test: hi
  strcmp: -11, 11, 01
  file test 1: success

  file test 2: success
  success

  Traceback (most recent call last):
    File "_ctypes/callbacks.c", line 314, in 'calling callback function'
    File "/usr/local/lib/python2.7/site-packages/unicorn/unicorn.py", line 249, in _hook_insn_syscall_cb
      cb(self, data)
    File "/Users/aegis/projects/usercorn/py/usercorn/cls.py", line 110, in hook_syscall
      self.os.syscall(self.uc)
    File "/Users/aegis/projects/usercorn/py/usercorn/arch/x64/darwin.py", line 26, in syscall
      ret = syscalls.call(cls, SYSCALLS, num, lambda n: args[:n])
    File "/Users/aegis/projects/usercorn/py/usercorn/syscalls.py", line 59, in call
      return f(cls, *args) or 0
    File "/Users/aegis/projects/usercorn/py/usercorn/syscalls.py", line 16, in write
      return os.write(a1, cls.mem_read(a2, a3))
    File "/usr/local/lib/python2.7/site-packages/unicorn/unicorn.py", line 189, in mem_read
      data = ctypes.create_string_buffer(size)
    File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 65, in create_string_buffer
      buftype = c_char * init
  ValueError: Array length must be >= 0, not -17958193

**Comment by lunixbochs** [comment]
Python frontend has been removed.
