### ISSUE TITLE
generate syscall lists

### ISSUE THREAD

**Issue by lunixbochs** [lunixbochs/usercorn#25]

**Comment by lunixbochs** [comment]
I shouldn't need to maintain these by hand. Make yaml files with numbers and argument types and generate per-language syscall lists.

**Comment by lunixbochs** [comment]
started here 91168bdb0fe7b50f46923dc8bd51bb02d69d73e8

**Comment by lunixbochs** [comment]
more here 88f4ff0e01d4984fa684727537a6e906d56cb8ef

still missing sparc, arm64, m68k

**Comment by lunixbochs** [comment]
moved to ghostrace, should migrate this issue

**Comment by petevine** [comment]
Where's that coming from?

`$ ./usercorn -strace /bin/ls`
panic: Syscall missing: 26872

```go
goroutine 17 [running, locked to thread]:
github.com/lunixbochs/usercorn/go.(*Usercorn).Syscall(0x106c62a0, 0x68f8, 0x0, 0x0, 0x1077a040, 0x1077a040, 0x4, 0x0, 0x0)
        /home/odroid/go/src/github.com/lunixbochs/usercorn/go/usercorn.go:670 +0x130
github.com/lunixbochs/usercorn/go/arch/arm.LinuxSyscall(0xabb2f680, 0x106c62a0, 0x68f8)
        /home/odroid/go/src/github.com/lunixbochs/usercorn/go/arch/arm/linux.go:115 +0xcc
github.com/lunixbochs/usercorn/go/arch/arm.LinuxInterrupt(0xabb2f680, 0x106c62a0, 0x2)
        /home/odroid/go/src/github.com/lunixbochs/usercorn/go/arch/arm/linux.go:129 +0x194
````

**Comment by lunixbochs** [comment]
Syscall lists come from my ghostrace project. I probably don't support all the ARM and MIPS ABI numberings yet.

**Comment by lunixbochs** [comment]
Also if I mask that syscall I get 248 which is probably a real syscall.
